// <auto-generated />
using ED.Assistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ED.Assistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260927062048_ImportBioScanRules")]
    partial class ImportBioScanRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ED.Assistant.Data.Biology.Atmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Atmospheres", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioCatalogVersion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceCommit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BioCatalogVersions", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("JournalName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JournalName")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BioGenera", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtmosphereRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxGravityG")
                        .HasColumnType("REAL");

                    b.Property<bool>("MaxOrbitalPeriodExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxOrbitalPeriodSeconds")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxPressureAtmospheres")
                        .HasColumnType("REAL");

                    b.Property<bool>("MaxPressureExclusive")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxTemperatureK")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinArrivalDistanceLs")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinGravityG")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinPressureAtmospheres")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinTemperatureK")
                        .HasColumnType("REAL");

                    b.Property<string>("Nebula")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFile")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolcanismMode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VolcanismRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.ToTable("BioSpawnRules", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleAtmosphere", b =>
                {
                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.HasKey("SpawnRuleId", "AtmosphereId", "Mode");

                    b.HasIndex("AtmosphereId");

                    b.ToTable("BioSpawnRuleAtmospheres", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleAtmosphereComponent", b =>
                {
                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinPercent")
                        .HasColumnType("REAL");

                    b.HasKey("SpawnRuleId", "AtmosphereId");

                    b.HasIndex("AtmosphereId");

                    b.ToTable("BioSpawnRuleAtmosphereComponents", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleBodyType", b =>
                {
                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.HasKey("SpawnRuleId", "BodyTypeId", "Mode");

                    b.HasIndex("BodyTypeId");

                    b.ToTable("BioSpawnRuleBodyTypes", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleStar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Luminosity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StarType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpawnRuleId");

                    b.ToTable("BioSpawnRuleStars", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleSystemBodyType", b =>
                {
                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SpawnRuleId", "BodyTypeId");

                    b.HasIndex("BodyTypeId");

                    b.ToTable("BioSpawnRuleSystemBodyTypes", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleVolcanism", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SpawnRuleId");

                    b.ToTable("BioSpawnRuleVolcanisms", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenusId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JournalName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinScanDistanceM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VariantDeterminantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("JournalName")
                        .IsUnique();

                    b.HasIndex("VariantDeterminantId");

                    b.HasIndex("GenusId", "Name")
                        .IsUnique();

                    b.ToTable("BioSpecies", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BodyTypes", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.VariantDeterminant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VariantDeterminants", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithMany("SpawnRules")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleAtmosphere", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.Atmosphere", "Atmosphere")
                        .WithMany("SpawnRules")
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("Atmospheres")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atmosphere");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleAtmosphereComponent", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.Atmosphere", "Atmosphere")
                        .WithMany()
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("AtmosphereComponents")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atmosphere");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleBodyType", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BodyType", "BodyType")
                        .WithMany("SpawnRules")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("BodyTypes")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleStar", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("Stars")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleSystemBodyType", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BodyType", "BodyType")
                        .WithMany()
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("SystemBodyTypes")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleVolcanism", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("VolcanismPatterns")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioGenus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.VariantDeterminant", "VariantDeterminant")
                        .WithMany("Species")
                        .HasForeignKey("VariantDeterminantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genus");

                    b.Navigation("VariantDeterminant");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.Atmosphere", b =>
                {
                    b.Navigation("SpawnRules");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.Navigation("AtmosphereComponents");

                    b.Navigation("Atmospheres");

                    b.Navigation("BodyTypes");

                    b.Navigation("Stars");

                    b.Navigation("SystemBodyTypes");

                    b.Navigation("VolcanismPatterns");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Navigation("SpawnRules");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BodyType", b =>
                {
                    b.Navigation("SpawnRules");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.VariantDeterminant", b =>
                {
                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
