// <auto-generated />
using ED.Assistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ED.Assistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508074356_MoveSpawnRuleBodyTypesToRelation")]
    partial class MoveSpawnRuleBodyTypesToRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ED.Assistant.Data.Biology.Atmosphere", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Atmospheres", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BioGenera", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtmosphereRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VolcanismRaw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId")
                        .IsUnique();

                    b.ToTable("BioSpawnRules", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleBodyType", b =>
                {
                    b.Property<int>("SpawnRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.HasKey("SpawnRuleId", "BodyTypeId", "Mode");

                    b.HasIndex("BodyTypeId");

                    b.ToTable("BioSpawnRuleBodyTypes", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GenusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinScanDistanceM")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VariantDeterminantId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("VariantDeterminantId");

                    b.HasIndex("GenusId", "Name")
                        .IsUnique();

                    b.ToTable("BioSpecies", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BodyType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BodyTypes", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.SpeciesAtmosphereCondition", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AtmosphereId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .HasColumnType("TEXT");

                    b.HasKey("SpeciesId", "AtmosphereId", "Mode");

                    b.HasIndex("AtmosphereId");

                    b.ToTable("SpeciesAtmosphereConditions", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.VariantDeterminant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VariantDeterminants", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithOne("SpawnRule")
                        .HasForeignKey("ED.Assistant.Data.Biology.BioSpawnRule", "SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRuleBodyType", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BodyType", "BodyType")
                        .WithMany("SpawnRules")
                        .HasForeignKey("BodyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpawnRule", "SpawnRule")
                        .WithMany("BodyTypes")
                        .HasForeignKey("SpawnRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyType");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioGenus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.VariantDeterminant", "VariantDeterminant")
                        .WithMany("Species")
                        .HasForeignKey("VariantDeterminantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genus");

                    b.Navigation("VariantDeterminant");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.SpeciesAtmosphereCondition", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.Atmosphere", "Atmosphere")
                        .WithMany("SpeciesConditions")
                        .HasForeignKey("AtmosphereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithMany("AtmosphereConditions")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atmosphere");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.Atmosphere", b =>
                {
                    b.Navigation("SpeciesConditions");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnRule", b =>
                {
                    b.Navigation("BodyTypes");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Navigation("AtmosphereConditions");

                    b.Navigation("SpawnRule");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BodyType", b =>
                {
                    b.Navigation("SpawnRules");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.VariantDeterminant", b =>
                {
                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
