// <auto-generated />
using ED.Assistant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ED.Assistant.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bio_genus", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GenusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("genus_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_url");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("species_id");

                    b.Property<int?>("VariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("VariantId");

                    b.ToTable("bio_reference", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bio_source", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Atmosphere")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("atmosphere");

                    b.Property<double?>("MaxDistanceFromStarLs")
                        .HasColumnType("REAL")
                        .HasColumnName("max_distance_from_star_ls");

                    b.Property<double?>("MaxGravityG")
                        .HasColumnType("REAL")
                        .HasColumnName("max_gravity_g");

                    b.Property<double?>("MaxPressureAtm")
                        .HasColumnType("REAL")
                        .HasColumnName("max_pressure_atm");

                    b.Property<double?>("MaxTemperatureK")
                        .HasColumnType("REAL")
                        .HasColumnName("max_temperature_k");

                    b.Property<double?>("MinDistanceFromStarLs")
                        .HasColumnType("REAL")
                        .HasColumnName("min_distance_from_star_ls");

                    b.Property<double?>("MinGravityG")
                        .HasColumnType("REAL")
                        .HasColumnName("min_gravity_g");

                    b.Property<double?>("MinPressureAtm")
                        .HasColumnType("REAL")
                        .HasColumnName("min_pressure_atm");

                    b.Property<double?>("MinTemperatureK")
                        .HasColumnType("REAL")
                        .HasColumnName("min_temperature_k");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("PlanetClass")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("planet_class");

                    b.Property<int?>("SpeciesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("species_id");

                    b.Property<int?>("VariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variant_id");

                    b.Property<string>("VolcanicActivity")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("volcanic_activity");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("VariantId");

                    b.ToTable("bio_spawn_condition", null, t =>
                        {
                            t.HasCheckConstraint("CK_bio_spawn_condition_species_or_variant", "species_id IS NOT NULL OR variant_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseValue")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_value");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int>("GenusId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("genus_id");

                    b.Property<int?>("MinScanDistanceM")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_scan_distance_m");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("GenusId", "Name")
                        .IsUnique();

                    b.ToTable("bio_species", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color_hex");

                    b.Property<string>("ColorName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("color_name");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("species_id");

                    b.HasKey("Id");

                    b.HasIndex("SpeciesId");

                    b.HasIndex("SpeciesId", "Name")
                        .IsUnique();

                    b.ToTable("bio_variant", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioVariantRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("material_name");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("RegionName")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("region_name");

                    b.Property<string>("StarClass")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("star_class");

                    b.Property<int>("VariantId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasIndex("MaterialName");

                    b.HasIndex("StarClass");

                    b.HasIndex("VariantId");

                    b.ToTable("bio_variant_rule", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioReference", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioGenus", "Genus")
                        .WithMany("References")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ED.Assistant.Data.Biology.BioSource", "Source")
                        .WithMany("References")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithMany("References")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ED.Assistant.Data.Biology.BioVariant", "Variant")
                        .WithMany("References")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Genus");

                    b.Navigation("Source");

                    b.Navigation("Species");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpawnCondition", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithMany("SpawnConditions")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ED.Assistant.Data.Biology.BioVariant", "Variant")
                        .WithMany("SpawnConditions")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Species");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioGenus", "Genus")
                        .WithMany("Species")
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genus");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioVariant", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioSpecies", "Species")
                        .WithMany("Variants")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioVariantRule", b =>
                {
                    b.HasOne("ED.Assistant.Data.Biology.BioVariant", "Variant")
                        .WithMany("Rules")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioGenus", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSource", b =>
                {
                    b.Navigation("References");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioSpecies", b =>
                {
                    b.Navigation("References");

                    b.Navigation("SpawnConditions");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ED.Assistant.Data.Biology.BioVariant", b =>
                {
                    b.Navigation("References");

                    b.Navigation("Rules");

                    b.Navigation("SpawnConditions");
                });
#pragma warning restore 612, 618
        }
    }
}
