// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ED.Assistant.Plugins.Explorer.Data.Migrations
{
    [DbContext(typeof(ExplorerDbContext))]
    [Migration("20261001090000_ExplorerInitial")]
    partial class ExplorerInitial
    {
    }
}
