// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ED.Assistant.Plugins.Explorer.Data.Migrations
{
    [DbContext(typeof(ExplorerDbContext))]
    partial class ExplorerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ED.Assistant.Plugins.Explorer.Data.ExplorerBody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodyId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateMapped")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateScanned")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateSold")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEfficientMapping")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsLost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMapped")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTerraformable")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MassEm")
                        .HasColumnType("REAL");

                    b.Property<string>("PlanetClass")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StarSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SystemAddress")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Value")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasDiscovered")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasMapped")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "DateScanned");

                    b.HasIndex("SystemAddress", "BodyId");

                    b.ToTable("ExplorerBody", (string)null);
                });

            modelBuilder.Entity("ED.Assistant.Plugins.Explorer.Data.ExplorerJournalCursor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ExplorerJournalCursor", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
